pull request from UVA pysumma notebook example
UW-Hydro/pysumma pull request #15
Opened 2018-03-05 21:32 UTC by DavidChoi76

2018-03-05 21:37 UTC, DavidChoi76 commented
@bartnijssen @arbennett could one of you review this pull request. it consists of one example notebook and supporting files.

2018-03-14 23:03 UTC, arbennett requested changes
I think it would be good to move the example notebook to a `notebooks` or `examples` directory so that it's easier to expand things out in the future.

2018-03-14 23:03 UTC, arbennett commented on pysumma/Simulation.py
> +    def execute(self,     run_suffix):
No need for extra spaces before `run_suffix`

2018-03-14 23:03 UTC, arbennett commented on pysumma/Simulation.py
>              cmd = "{} -p never -s {}       -m {}".format(self.executable, self.run_suffix, self.filepath)
No need for extra spaces before `-m`

2018-03-14 23:03 UTC, arbennett commented on pysumma/Simulation.py
> +            out_file_path = 	self.output_path.filepath + \
This is somewhat brittle, but maybe beyond the scope of this pull request.  We should figure out a better way to pick up where output comes from.  I'll open an issue on this topic.  I think it's fine here for now, though.

2018-03-21 03:09 UTC, DavidChoi76 commented
@arbennett :  I changed your requests. Sorry. It's too late.

2018-03-22 04:45 UTC, arbennett approved these changes

2018-03-22 04:45 UTC, merged